name: reddit-engagement-analyzer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - emoji
  - pytest
  - ipykernel
  - seaborn
  - altair
  - pyyaml
  - black
  - ruff
  - nltk
  - pip
  - pip:
      - openai>=1.0
      - streamlit>=1.20
      - python-dotenv>=1.0.0
